### ISSUE TITLE
Installer

### ISSUE THREAD

**Issue by exocet72** [RushScript/MSFS-PBR#11]
HI I Can not install this at all, My antivirus keeps cutting in and deleting the .exe

Ignor this please.Just after I submitted this post I got the all clear from AV. So all is good thanks

**Comment by RushScript** [comment]
Unfortunately some AV detect the executable as a false positive. If it happens again please share a screenshot with your AV detection details so i can report it as a false positive.

Feel free to re-open the ticket if you need anything else.
